default_seed: 42
dataset:
   data_dir: "/exeh_4/yuping/Epistasis_Interaction/00_Generate_Data/results"
   phentoype_dir: "/mnt/data/share/yuping/data/phenotype_info.csv"
   env_dir: "/mnt/data/share/yuping/data/env_info.csv"
model_params:
   n_estimators: [500]
   max_features: [40, 50, 60, 70] 
